---
title: "R Notebook"
output: html_notebook
---



```{r}
library(mice)
library(dplyr)
library(ggplot2)
```
```{r}
# Read in raw data
raw=read.csv('data/Ames_Housing_Price_Data.csv')[,-1]
```
```{r}
summary(raw)
head(raw)
```
```{r}
# Read in categorical variables as empty strings instead of NA
unique(raw$FireplaceQu)
# Change to NA
raw[raw=='']=NA
```


```{r}
# Remove Misc Features
rawd = select(raw,-MiscFeature)
```


```{r}
mice::md.pattern(rawd, rotate.names=TRUE)
```



```{r}
# log trasform Target and GrLivArea
raw_tlog = raw
raw_tlog[, 3] = log(raw[3], 2)
raw_tlog$GrLivArea = log(raw$GrLivArea)
```

## Mapping different categorical variables to Saleprice to GrLivArea
```{r}
# House styles like floors
raw_tlog%>% 
  ggplot(aes(x=GrLivArea, y=SalePrice)) +
  geom_point(aes(color = HouseStyle ))
```
```{r}
# Basement quality
raw_tlog%>% 
  ggplot(aes(x=GrLivArea, y=SalePrice)) +
  geom_point(aes(color = BsmtQual))
```
```{r}
# year - need to calculate age
raw_tlog%>% 
  ggplot(aes(x=GrLivArea, y=SalePrice)) +
  geom_point(aes(color = YearBuilt))
```
```{r}
# Kitchen quality
raw%>% 
  ggplot(aes(x=GrLivArea, y=SalePrice)) +
  geom_point(aes(color =KitchenQual))
```

# Exploring Aikos question
```{r}
(10^2.085)

```

```{r}
10^1.47067899
```

### Trying stepwise AIC, BIC
```{r}
df=read.csv('data/cleanforRd.csv')
```

```{r}
#summary(df)
head(df)
```
```{r}
library(corrplot)
```

```{r}
cor_mat = cor(df)
corrplot(cor_mat, method="circle", type="lower")
```

```{r}
# Creating a saturated model (i.e., with all variables included).
model.saturated = lm(SalePrice ~ ., data = df)
```

```{r}
summary(model.saturated)
```

```{r}
library(car)
vif(model.saturated)
```

```{r}
model.empty = lm(SalePrice ~ 1, data = df) #The model with an intercept ONLY.
scope = list(lower = formula(model.empty), upper = formula(model.saturated))

backwardAIC = step(model.saturated, scope, direction = "backward", k = 2)
# Step:  AIC=-28.16
# Life.Exp ~ Population + Murder + HS.Grad + Frost
```
```{r}
forwardAIC = step(model.empty, scope, direction = "forward", k = 2)
```

```{r}
plot(forwardAIC)
```
```{r}
backwardBIC = step(model.saturated, scope, direction = "backward", k = log(50))
```



```{r}
forwardBIC = step(model.empty, scope, direction = "forward", k = log(50))
```



```{r}

formula(backwardBIC)
formula(forwardAIC)
formula(forwardBIC)
```
```{r}
plot(forwardBIC)
```
```{r}
summary(forwardAIC)
```


```{r}
vif(forwardBIC)
```

```{r}
vif(forwardAIC)
```

#### LOG TRANSFORM TARGET

```{r}
head(df)
df_log = df
df_log$SalePrice = log(df$SalePrice)
```
```{r}
# log price saturated model
model.saturated.log = lm(SalePrice ~ ., data = df_log)
```

```{r}
model.empty.log = lm(SalePrice ~ 1, data = df_log) #The model with an intercept ONLY.
scope = list(lower = formula(model.empty.log), upper = formula(model.saturated.log))

fowardBIClog = step(model.empty.log, scope, direction = "forward", k = log(50))
```
```{r}
formula(fowardBIClog)
```
```{r}
vif(fowardBIClog)
```

```{r}
summary(fowardBIClog)
```
### Running BIC again with insights
```{r}
df_i=read.csv('data/cleanforR_i.csv', stringsAsFactors = TRUE)
```

```{r}
head(df_i)
```
```{r}
model.saturated.insights = lm(SalePrice ~ ., data = df_i)
```

```{r}
model.empty.i = lm(SalePrice ~ 1, data = df_i) #The model with an intercept ONLY.
scope = list(lower = formula(model.empty.i), upper = formula(model.saturated.insights))

fowardBICi = step(model.empty.i, scope, direction = "forward", k = log(50))

```


```{r}
formula(fowardBICi)
```
```{r}
vif(fowardBICi)
```
```{r}
summary(fowardBICi)
```
```{r}
plot(fowardBICi)
```


############################################################################
After Talk 

```{r}
df_at=read.csv('data/rdata_at.csv')
df_atl=read.csv('data/rdata_atl.csv')
```

```{r}
#summary(df)
head(df_atl)
```



```{r}
# Creating a saturated model (i.e., with all variables included).
model.sat.at = lm(SalePrice ~ ., data = df_at)
model.sat.atl = lm(SalePrice ~ ., data = df_atl)
```

```{r}
summary(model.sat.at)
summary(model.sat.atl)
```

```{r}
vif(model.sat.atl)
```

```{r}
model.empty.at = lm(SalePrice ~ 1, data = df_at) #The model with an intercept ONLY.
model.empty.atl = lm(SalePrice ~ 1, data = df_atl)

scope_at = list(lower = formula(model.empty.at), upper = formula(model.sat.at))
scope_atl = list(lower = formula(model.empty.atl), upper = formula(model.sat.atl))
```


```{r}
forwardBIC_at = step(model.empty.at, scope_at, direction = "forward", k = log(50))
```

```{r}
formula(forwardBIC_at)
```

```{r}
forwardBIC_atl = step(model.empty.atl, scope_atl, direction = "forward", k = log(50))
```

```{r}
formula(forwardBIC_atl)
```


```{r}
summary(forwardBIC_at)
summary(forwardBIC_atl)
```

```{r}
plot(forwardBIC_at)
plot(forwardBIC_atl)
```
```{r}
vif(forwardBIC_at)
vif(forwardBIC_atl)
```

